//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LayoutsFromModel.Properties {
	using System;
	
	
	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	public class CmdPrompts {
		
		private static global::System.Resources.ResourceManager resourceMan;
		
		private static global::System.Globalization.CultureInfo resourceCulture;
		
		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal CmdPrompts() {
		}
		
		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LayoutsFromModel.Properties.CmdPrompts", typeof(CmdPrompts).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}
		
		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Задайте номер первого Layout: .
		/// </summary>
		public static string FirstLayoutNumber {
			get {
				return ResourceManager.GetString("FirstLayoutNumber", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Дайте первую точку рамки: .
		/// </summary>
		public static string FrameFirstPointQuery {
			get {
				return ResourceManager.GetString("FrameFirstPointQuery", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Дайте противоположную точку рамки: .
		/// </summary>
		public static string FrameOppositePointQuery {
			get {
				return ResourceManager.GetString("FrameOppositePointQuery", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Укажите файл шаблона.
		/// </summary>
		public static string TemplateFileQuery {
			get {
				return ResourceManager.GetString("TemplateFileQuery", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Шаблон (*.dwg, *.dwt)|*.dwg;*.dwt.
		/// </summary>
		public static string TemplateFileQueryFilter {
			get {
				return ResourceManager.GetString("TemplateFileQueryFilter", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Используем шаблон .
		/// </summary>
		public static string UsingTemplate {
			get {
				return ResourceManager.GetString("UsingTemplate", resourceCulture);
			}
		}
	}
}
